name: CI + CD

on:
  pull_request:
    branches: [ main ]
    
jobs:   
  DeployUAT:
    name: Deploy to UAT
    runs-on: windows-latest
    environment: UAT
    steps:
      - name: SP Lists Migration
        uses: ./.github/workflows/MigrateSPLists.yml
        with:
            SHAREPOINT_SOURCE_SITE: ${{  vars.SHAREPOINT_SOURCE_SITE }}
            SHAREPOINT_TARGET_SITE: ${{  vars.SHAREPOINT_TARGET_SITE }} 
            MEAFUSION_PFX_PASSWORD: ${{ secrets.MEAFUSION_PFX_PASSWORD }}
            MEAFUSION_PFX : ${{ secrets.MEAFUSION_PFX }}
  DeployProd:
    name: Deploy to Production 
    needs: [DeployUAT]   
    runs-on: windows-latest
    environment: PROD
    steps:
      - name: SP Lists Migration
        uses: ./.github/workflows/MigrateSPLists.yml
        with:
            SHAREPOINT_SOURCE_SITE: ${{  vars.SHAREPOINT_SOURCE_SITE }}
            SHAREPOINT_TARGET_SITE: ${{  vars.outputs.SHAREPOINT_TARGET_SITE }} 
            MEAFUSION_PFX_PASSWORD: ${{ secrets.MEAFUSION_PFX_PASSWORD }}
            MEAFUSION_PFX : ${{ secrets.MEAFUSION_PFX }}
