name: CI + CD

on:
  pull_request:
    branches: [ main ]
    
jobs:
  get-env-vars:
    name: Get Environment vars for each deployment stage
    runs-on: windows-latest
    steps:
      - name: retrieve env vars for uat
        id: uat-id
        shell: pwsh
        run: |
          $headers = @{
                    "Accept" = "application/vnd.github+json"
                    "Authorization" = "Bearer ${{ secrets.GITHUB_TOKEN }}"
                  }
          $url = "https://api.github.com/repositories/${{ github.repository }}/environments/UAT/variables"
          $response = Invoke-RestMethod -Uri $url -Headers $headers -Method Get
          # Loop through the variables in the response and set each as an output
          foreach ($variable in $response.variables) {
            $variableName = $variable.name
            $variableValue = $variable.value
            # Set the output variable in the format "::set-output name=VARIABLE_NAME::VARIABLE_VALUE"
            Write-Host "::set-output name=$variableName::$variableValue"
          }
      - name: retrieve env vars for PROD
        id: prod-id
        shell: pwsh
        run: |
          $headers = @{
                    "Accept" = "application/vnd.github+json"
                    "Authorization" = "Bearer ${{ secrets.GITHUB_TOKEN }}"
                  }
          $url = "https://api.github.com/repositories/${{ github.repository }}/environments/PROD/variables"
          $response = Invoke-RestMethod -Uri $url -Headers $headers -Method Get
          # Loop through the variables in the response and set each as an output
          foreach ($variable in $response.variables) {
            $variableName = $variable.name
            $variableValue = $variable.value
            # Set the output variable in the format "::set-output name=VARIABLE_NAME::VARIABLE_VALUE"
            Write-Host "::set-output name=$variableName::$variableValue"
          }

  DeployUAT:
    needs: [get-env-vars]
    name: Deploy to UAT 
    uses: ./.github/workflows/MigrateSPLists.yml
    with:
      ENVIRONMENT: UAT
      SHAREPOINT_SOURCE_SITE: ${{  needs.get-env-vars.steps.uat-id.outputs.SHAREPOINT_SOURCE_SITE }}
      SHAREPOINT_TARGET_SITE: ${{  needs.get-env-vars.steps.uat-id.outputs.SHAREPOINT_TARGET_SITE }}
    secrets: 
      MEAFUSION_PFX_PASSWORD: ${{ secrets.MEAFUSION_PFX_PASSWORD }}
      MEAFUSION_PFX : ${{ secrets.MEAFUSION_PFX }}
      
  DeployProd:
    needs: [DeployUAT]
    name: Deploy to PROD 
    uses: ./.github/workflows/MigrateSPLists.yml
    with:
      ENVIRONMENT: PROD
      SHAREPOINT_SOURCE_SITE: ${{  needs.get-env-vars.steps.prod-id.outputs.SHAREPOINT_SOURCE_SITE }}
      SHAREPOINT_TARGET_SITE: ${{  needs.get-env-vars.steps.prod-id.outputs.SHAREPOINT_TARGET_SITE }}
    secrets: 
      MEAFUSION_PFX_PASSWORD: ${{ secrets.MEAFUSION_PFX_PASSWORD }}
      MEAFUSION_PFX : ${{ secrets.MEAFUSION_PFX }}
