name: CI + CD

on:
  pull_request:
    branches: [ main ]

jobs:
  job1:
    outputs:
      myoutput: ${{ steps.step1.outputs.myoutput }}
    runs-on: windows-latest
    steps:
    - name: set output
      id: step1
      run: |
        echo "myoutput='hello world'" >> $GITHUB_OUTPUT

  job2:
    needs: job1
    runs-on: windows-latest
    steps:
    - name: retrieve output
      run: |
        echo ${{ needs.job1.outputs.myoutput }}
