name: CI + CD PP

on:
  pull_request:
    branches: [main]
    paths: 
      - PowerPlatform/**
      
permissions:
  contents: write

jobs:
  
  UAT_DATA_MIGRATION: 
    runs-on: windows-latest
    environment: UAT
    steps: 
       - name: Power Platform Action Install
         uses: microsoft/powerplatform-actions/actions-install@v1
       - uses: actions/checkout@v3
         with:
          lfs: true
       - name : DEBUG
         run:  ls ./PowerPlatform/data
       - name: import-data
         uses: microsoft/powerplatform-actions/import-data@v1
         with:
          environment-url: ${{vars.ENVIRONMENT_URL}}
          app-id: ${{vars.CLIENT_ID}}
          client-secret: ${{secrets.SPN}}
          tenant-id: ${{vars.TENANT_ID}}
          data-file: ./PowerPlatform/data
   

  
