name: CI + CD

on:
  pull_request:
    branches: [ main ]
    
jobs:      
  DeployUAT:
    name: Deploy to UAT 
    uses: ./.github/workflows/MigrateSPLists.yml
    with:
      ENVIRONMENT: UAT
    secrets: 
      MEAFUSION_PFX_PASSWORD: ${{ secrets.MEAFUSION_PFX_PASSWORD }}
      MEAFUSION_PFX : ${{ secrets.MEAFUSION_PFX }}
  DeployProd:
    name: Deploy to Production 
    needs: [DeployUAT]
    uses: ./.github/workflows/MigrateSPLists.yml
    with:
          ENVIRONMENT: PROD      
    secrets: 
      MEAFUSION_PFX_PASSWORD: ${{ secrets.MEAFUSION_PFX_PASSWORD }}
      MEAFUSION_PFX : ${{ secrets.MEAFUSION_PFX }}
