name: CI + CD

on:
  pull_request:
    branches: [ main ]
    
jobs:      
  DeployUAT:
    name: Deploy to UAT 
    uses: ./.github/workflows/MigrateSPLists.yml
    with:
          ENVIRONMENT: UAT       
  DeployProd:
    name: Deploy to Production 
    needs: [DeployUAT]
    uses: ./.github/workflows/MigrateSPLists.yml
    with:
          ENVIRONMENT: PROD      
    
