name: CI + CD

on:
  pull_request:
    branches: [ main ]
    
jobs:      
  DeployUAT:
    name: Deploy to UAT 
    runs-on: windows-latest
    environment: 
      name: UAT
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
            
  DeployProd:
    name: Deploy to Production 
    needs: [DeployUAT]
    runs-on: windows-latest
    environment: 
      name: PROD
    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      uses: ./.github/workflows/MigrateSPLists.yml
    
