name: CI + CD PP

on:
  pull_request:
    branches: [main]
    paths: 
      - PowerPlatform/**
      
permissions:
  contents: write

jobs:
  UAT_Deployment:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      solution_name: PPALMPOC
      BUILD_ENVIRONMENT_URL: 'https://org158aa323.crm4.dynamics.com'
      ENVIRONMENT: UAT
    secrets:
      CLIENT_SECRET: ${{secrets.SPN}}
  
  UAT_DATA_MIGRATION: 
    needs: [UAT_Deployment]
    runs-on: windows-latest
    environment: UAT
    steps: 
       - name: export-data
         uses: microsoft/powerplatform-actions/export-data@v1
         with:
          environment-url: ${{vars.ENVIRONMENT_URL}}
          app-id: ${{vars.CLIENT_ID}}
          client-secret: ${{secrets.SPN}}
          tenant-id: ${{vars.TENANT_ID}}
          data-file: PowerPlatform/data/data.zip

  PROD_Deployment:
    needs: [UAT_DATA_MIGRATION]
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      solution_name: PPALMPOC
      BUILD_ENVIRONMENT_URL: 'https://org158aa323.crm4.dynamics.com'
      ENVIRONMENT: PROD
    secrets:
      CLIENT_SECRET: ${{secrets.SPN}}
   

  PROD_DATA_MIGRATION: 
      needs: [PROD_Deployment]
      runs-on: windows-latest
      environment: PROD
      steps: 
       - name: export-data
         uses: microsoft/powerplatform-actions/export-data@v1
         with:
          environment-url: ${{vars.ENVIRONMENT_URL}}
          app-id: ${{vars.CLIENT_ID}}
          client-secret: ${{secrets.SPN}}
          tenant-id: ${{vars.TENANT_ID}}
          data-file: PowerPlatform/data/data.zip
