name: CI + CD

on:
  pull_request:
    branches: [ main ]
    
jobs:
  get-env-vars:
    name: Get Environment vars
    runs-on: windows-later
    outputs:
      SHAREPOINT_SOURCE_SITE: ${{env.SHAREPOINT_SOURCE_SITE}}
      SHAREPOINT_TARGET_SITE: ${{env.SHAREPOINT_TARGET_SITE}}
    steps:
      - run: echo "null"
  DeployUAT:
    needs: [get-env-vars]
    name: Deploy to UAT 
    uses: ./.github/workflows/MigrateSPLists.yml
    with:
      ENVIRONMENT: UAT
      SHAREPOINT_SOURCE_SITE: ${{  needs.get-env.outputs.SHAREPOINT_SOURCE_SITE }}
      SHAREPOINT_TARGET_SITE: ${{  needs.get-env.outputs.SHAREPOINT_TARGET_SITE }}
    secrets: 
      MEAFUSION_PFX_PASSWORD: ${{ secrets.MEAFUSION_PFX_PASSWORD }}
      MEAFUSION_PFX : ${{ secrets.MEAFUSION_PFX }}
  DeployProd:
    name: Deploy to Production 
    needs: [DeployUAT]
    uses: ./.github/workflows/MigrateSPLists.yml
    with:
          ENVIRONMENT: PROD
          SHAREPOINT_SOURCE_SITE: ${{  needs.get-env.outputs.SHAREPOINT_SOURCE_SITE }}
          SHAREPOINT_TARGET_SITE: ${{  needs.get-env.outputs.SHAREPOINT_TARGET_SITE }}
    secrets: 
      MEAFUSION_PFX_PASSWORD: ${{ secrets.MEAFUSION_PFX_PASSWORD }}
      MEAFUSION_PFX : ${{ secrets.MEAFUSION_PFX }}
