name: CI + CD

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:      
  DeployUAT:
    name: Deploy to UAT 
    runs-on: windows-latest
    environment: 
      name: UAT
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Deploy
        uses: ./MigrateSPLists.yml
            
  DeployProd:
    name: Deploy to Production 
    needs: [DeployUAT]
    runs-on: windows-latest
    environment: 
      name: PROD
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Deploy
      uses: ./MigrateSPLists.yml 
    
