name: CI + CD

on:
  pull_request:
    branches: [ main ]
    
jobs:
  job1:
    runs-on: windows-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: Write-Host "::set-output name=test::hello"
      - id: step2
        run: Write-Host "::set-output name=test::word"
  job2:
    runs-on: windows-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
