name: CI + CD

on:
  pull_request:
    branches: [ main ]

jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Set an output variable in job1
        id: set-output-job1
        run: |
          # This is job1
          # Perform some actions...
          
          # Set an output variable named 'my_output_var' with a value
          echo "::set-output name=my_output_var::This is the output from job1"

  job2:
    runs-on: windows-latest
    needs: job1  # Ensure job2 runs after job1
    steps:
      - name: Get the output variable from job1
        id: get-output-job1
        run: |
          # This is job2
          # Get the output variable from job1 using ${{ needs.job1.outputs.my_output_var }}
          echo "The output from job1 is: ${{ needs.job1.outputs.my_output_var }}"
