name: integration-tests

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        required: true
        type: string

jobs:
  testExecution:
    name: Run test plan
    runs-on: windows-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-dotnet@v3
      - name: install pac
        run: dotnet tool install --global Microsoft.PowerApps.CLI.Tool
      - name: create auth
        run: pac auth create --url ${{vars.ENVIRONMENT_URL}} --username ${{secrets.testUser1Name}} --password ${{secrets.testUser1Password}}
        
