name: Migrate SP Lists
on: [workflow_dispatch]
jobs:
    build:
      name: Run Script
      runs-on: windows-latest
      steps:
        - name: Script
          env: 
              MEAFUSION_PFX_PASSWORD: ${{ secrets.MEAFUSION_PFX_PASSWORD }}
          run: .\migrateList.ps1
          shell: powershell
        
