name: Migrate SP Lists
on:
  workflow_call:
    inputs:
          ENVIRONMENT:
                required: true
                type: string    

jobs:
    SP_Lists_Migration:
      name: Run SP Migration Script
      runs-on: windows-latest
      environment: ${{ inputs.ENVIRONMENT }}
      steps:
        - uses: actions/checkout@v3
        - name: Install and cache PowerShell modules
          uses: potatoqualitee/psmodulecache@v5.2
          with:
           modules-to-cache: PnP.PowerShell:1.12.0
           shell: powershell
        - name: MigrateSPLists
          env: 
              MEAFUSION_PFX_PASSWORD: ${{ secrets.MEAFUSION_PFX_PASSWORD }}
              MEAFUSION_PFX : ${{ secrets.MEAFUSION_PFX }}
              SP_SITE_SOURCE: ${{env.SHAREPOINT_SOURCE_SITE}}
              SP_SITE_TARGET: ${{env.SHAREPOINT_TARGET_SITE}}
          run: .\SharePoint\migrateList.ps1
          shell: powershell
        
